# Site settings
title: SP 1500-103 Voter Records Interchange Common Data Format Specification Draft Version 1.0
description: "SP 1500-103 Voter Records Interchange Common Data Format Specification Draft Version 1.0"
baseurl: "/VoterRecordsInterchange" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# GitHub information
org_name: usnistgov
repo_name: VoterRecordsInterchange

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /VoterRecordsInterchange/

host: 0.0.0.0
